In [2]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\aryan\Projects\data_engineering\daily-tasks\2026-02-23\sales_data.csv")



Q1. Display:
  - the number of rows and columns
  - the data types of each column
  - any missing values per column

In [6]:
print(f"The number of rows: {df.shape[0]}, columns: {df.shape[1]}")
print(f"The datatype of each column: {df.info()}")
print(f"Missing values: {df.isna().sum()}")

The number of rows: 30, columns: 11
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       30 non-null     int64
 1   customer_name  30 non-null     object
 2   age            30 non-null     int64
 3   city           30 non-null     object
 4   product        30 non-null     object
 5   category       30 non-null     object
 6   quantity       30 non-null     int64
 7   unit_price     30 non-null     float64
 8   discount_pct   30 non-null     int64
 9   order_date     30 non-null     object
 10  status         30 non-null     object
dtypes: float64(1), int64(4), object(6)
memory usage: 2.7+ KB
The datatype of each column: None
Missing values: order_id         0
customer_name    0
age              0
city             0
product          0
category         0
quantity         0
unit_price       0
discount_pct     0
order_date       0
status           0
dtype: int64

Q2. Add a new column called revenue which equals:

    quantity * unit_price * (1 - discount_pct / 100)
    Round to 2 decimal places using numpy.
    Then print the min, max, and mean revenue.

In [7]:
df.head()

,order_id,customer_name,age,city,product,category,quantity,unit_price,discount_pct,order_date,status
0,1001,Alice Johnson,28,New York,Laptop,Electronics,1,1200.0,10,2024-01-05,Completed
1,1002,Bob Smith,34,Los Angeles,Headphones,Electronics,2,85.5,5,2024-01-08,Completed
2,1003,Carol White,22,Chicago,Python Book,Books,3,45.0,0,2024-01-10,Completed
3,1004,David Brown,45,Houston,Office Chair,Furniture,1,320.0,15,2024-01-12,Cancelled
4,1005,Eva Martinez,31,Phoenix,Keyboard,Electronics,2,75.0,0,2024-01-15,Completed

In [9]:
df['revenue'] = df['quantity'] * df['unit_price'] * (1 - df['discount_pct'] / 100)
rounded_revenue = np.round(df['revenue'], decimals=2)
print(f"max revenue: {np.max(rounded_revenue)}")
print(f"min revenue: {np.min(rounded_revenue)}")
print(f"mean revenue: {np.mean(rounded_revenue)}")

max revenue: 1215.0
min revenue: 45.0
mean revenue: 376.9566666666667

Q3. Filter the DataFrame to show only:

    - Orders with status == "Completed" AND categroy == "Electronics"
    - From those, find the top 3 orders by revenue (highest first)

In [12]:
df.loc[( df['status']=="Completed" ) & ( df['status']=="Completed" )] \
    .sort_values(by='revenue', ascending=False) \
    .head(3)

,order_id,customer_name,age,city,product,category,quantity,unit_price,discount_pct,order_date,status,revenue
11,1012,Liam Thomas,36,Jacksonville,Laptop,Electronics,1,1350.0,10,2024-02-05,Completed,1215.0
0,1001,Alice Johnson,28,New York,Laptop,Electronics,1,1200.0,10,2024-01-05,Completed,1080.0
19,1020,Tina Clark,40,Nashville,Laptop,Electronics,1,999.0,0,2024-03-01,Completed,999.0

Q4. Group by category and compute:
  
- Total revenue
- Average discount percentage
- Number of orders

  Sort results by total revenue descending.

In [19]:
print( f"Total revenue:{  df.groupby('category')['revenue'].agg('sum')  } \n")
print( f"Average Discount percentage:{  df.groupby('category')['discount_pct'].agg('mean')  } \n")
print( f"Number of orders:{  df.groupby('category')['order_id'].agg('sum')  } \n")

Total revenue:category
Books           634.5
Electronics    7232.2
Furniture      3442.0
Name: revenue, dtype: float64

Average Discount percentage:category
Books          0.833333
Electronics    7.058824
Furniture      7.857143
Name: discount_pct, dtype: float64

Number of orders:category
Books           6096
Electronics    17267
Furniture       7102
Name: order_id, dtype: int64

Q5. Using the order_date column:

    - Extract the month name into a new column called month
    - Find which month had the highest total revenue

In [22]:
df['order_date'] = pd.to_datetime( df['order_date'], errors='coerce' )

In [25]:
df['month'] = df['order_date'].dt.month_name()
print("highest total revenue: \n", df.groupby('month')['revenue'].agg('max') )

highest total revenue:
 month
February    1215.0
January     1080.0
March        999.0
Name: revenue, dtype: float64

Q6. Using numpy (not pandas built-ins):

   - Compute the 25th, 50th, and 75th percentile of unit_price
   - Flag orders where revenue is above the 75th percentile
     as "High Value" and others as "Standard" in a new column order_tier

In [27]:
print("25th: ", np.quantile( df['unit_price'] , 0.25) )
print("50th: ", np.quantile( df['unit_price'] , 0.50) )
print("75th: ", np.quantile( df['unit_price'] , 0.75) )

25th:  62.5
50th:  115.0
75th:  535.0

In [29]:
df['order_tier'] = np.where(df['revenue'] > np.quantile(df['unit_price'], 0.75), "High Value", "Standard")
df.head()

,order_id,customer_name,age,city,product,category,quantity,unit_price,discount_pct,order_date,status,revenue,month,order_tier
0,1001,Alice Johnson,28,New York,Laptop,Electronics,1,1200.0,10,2024-01-05,Completed,1080.00,January,High Value
1,1002,Bob Smith,34,Los Angeles,Headphones,Electronics,2,85.5,5,2024-01-08,Completed,162.45,January,Standard
2,1003,Carol White,22,Chicago,Python Book,Books,3,45.0,0,2024-01-10,Completed,135.00,January,Standard
3,1004,David Brown,45,Houston,Office Chair,Furniture,1,320.0,15,2024-01-12,Cancelled,272.00,January,Standard
4,1005,Eva Martinez,31,Phoenix,Keyboard,Electronics,2,75.0,0,2024-01-15,Completed,150.00,January,Standard

Q7. Create a pivot table showing total revenue
    for each category × status combination.
    Fill missing values with 0.

In [34]:
df.pivot_table(index='category', columns='status', values='revenue', aggfunc='sum', fill_value=0)

status       Cancelled  Completed  Pending
category
Books              0.0      634.5      0.0
Electronics      114.0     7118.2      0.0
Furniture       1296.0      624.0   1522.0

Q8. Load the final cleaned DataFrame (with revenue and order_tier)
    into a  database called sales.db, table name orders.
    Then:

  - Query and print the total revenue per category using SQL
  - Query and print all cancelled orders

In [ ]:
import sqlite3

# Create connection to sales.db (creates file if it doesn't exist)
conn = sqlite3.connect('sales.db')

# Load DataFrame into 'orders' table
# Use if_exists='replace' to overwrite the table if you run this multiple times
df.to_sql('orders', conn, if_exists='replace', index=False)

In [ ]:
query_revenue = "SELECT category, SUM(revenue) as total_revenue FROM orders GROUP BY category"
revenue_per_cat = pd.read_sql(query_revenue, conn)

print("Total Revenue per Category:")
print(revenue_per_cat)

In [ ]:
query_cancelled = "SELECT * FROM orders WHERE status = 'Cancelled'"
cancelled_orders = pd.read_sql(query_cancelled, conn)

print("\nCancelled Orders:")
print(cancelled_orders)

# Always close the connection when finished
conn.close()